# Generated by Django 4.2.3 on 2023-07-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogModel',
        ),
    ]
