# Generated by Django 4.2.3 on 2023-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
    ]
