# Generated by Django 4.2.3 on 2023-07-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_blogcomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='time',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
